### ISSUE TITLE
Hololens ARamis Player

### ISSUE THREAD

**Issue by ChristianBar** [robyanne92/yaaaarrramis#27]
Far funzionare l'emulatore di Hololens con Unity, poi seguire gli stessi passi della versione ML: vedere issue #21, #22, #24, #23, #25

**Comment by robyanne92** [comment]
Ho diviso il problema in più issues sulla falsariga di quelle del ML (#29, #30, #31, #32, #33)

**Comment by ChristianBar** [comment]
👍
